### ISSUE TITLE
Cannot change hotkey in settings.

### ISSUE THREAD

**Issue by ted1922** [mipmip/gnome-shell-extensions-hotkeys-popup#3]
When attempting to change the Shortcut Keybinding, no input is detected and the box remains with the text 'New Accelerator'. Have tried with Super, Alt & Crtl as modifier keys, these do not change the box but instead function normally. Am unable to interact with the window, including using a mouse, until hitting Backspace which returns the default Super+H binding. 

![image](https://user-images.githubusercontent.com/59594230/139960015-4ff6a893-e9c5-459b-ad9d-3ec16ca42c86.png)

Using **Gnome 40.4.0 & 5.14.15-arch1-1**, latest version from extensions.gnome.org used. 
Other extensions installed, 
![image](https://user-images.githubusercontent.com/59594230/139960624-9511fe66-a6e3-4409-b34e-117d4e6b005d.png)

**Comment by mipmip** [comment]
Thanks for your report. I have other with this control. Will address this in the next version.

**Comment by mipmip** [comment]
For the time being you can use this workaround command:
```
# set Super+s
gsettings --schemadir \ 
    ~/.local/share/gnome-shell/extensions/hotkeys-popup@pimsnel.com/schemas/ \ 
    set org.gnome.shell.extensions.hotkeys-popup \
    keybinding-show-popup "['<Super>s']"
```
